# Default configuration for the diabetes LSTM pipeline
# This file will be populated with actual configuration parameters

# Data configuration
data:
  raw_data_path: "data/raw"
  processed_data_path: "data/processed"
  dataset_url: "https://prod-dcd-datasets-cache-zipfiles.s3.eu-west-1.amazonaws.com/gk9m674wcx-1.zip"
  force_download: false # Set to true to force re-download even if data exists

# Logging configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/pipeline.log"

# Model configuration
model:
  sequence_length: 60
  prediction_horizon: 1
  lstm_units: [128, 64] # List of LSTM layer units
  dropout_rate: 0.2
  recurrent_dropout: 0.1
  dense_units: [64, 32] # List of dense layer units
  activation: "relu"
  output_activation: "linear"
  learning_rate: 0.001
  l1_regularization: 0.0
  l2_regularization: 0.001

# Training configuration
training:
  batch_size: 32
  epochs: 5
  validation_split: 0.2
  early_stopping_patience: 15
  lr_patience: 7

# Random seed for reproducibility
random_seed: 42

# Data validation configuration
validation:
  report_output_dir: "reports"
  zscore_threshold: 3.0
  contamination: 0.1 # For isolation forest
  required_columns:
    - "EventDateTime"
    - "DeviceMode"
    - "BolusType"
    - "Basal"
    - "CorrectionDelivered"
    - "TotalBolusInsulinDelivered"
    - "FoodDelivered"
    - "CarbSize"
    - "CGM"

# Data preprocessing configuration
preprocessing:
  missing_values:
    strategies:
      CGM: "interpolation"
      Basal: "forward_fill"
      TotalBolusInsulinDelivered: "zero_fill"
      CorrectionDelivered: "zero_fill"
      FoodDelivered: "zero_fill"
      CarbSize: "zero_fill"
    interpolation_method: "linear"
    max_gap_minutes: 30

  outliers:
    detection_methods: ["iqr", "zscore"]
    treatment_method: "clip"
    zscore_threshold: 3.0
    iqr_multiplier: 1.5
    contamination: 0.1
    column_settings:
      CGM:
        min_value: 40
        max_value: 400
        detection_methods: ["iqr", "zscore", "domain_specific"]
        treatment_method: "clip"

  cleaning:
    duplicate_strategy: "keep_last"
    time_tolerance_seconds: 60
    participant_column: "participant_id"

  resampling:
    target_frequency: "5min" # 5 minutes
    participant_column: "participant_id"
    aggregation_methods:
      CGM: "mean"
      Basal: "mean"
      TotalBolusInsulinDelivered: "sum"
      CorrectionDelivered: "sum"
      FoodDelivered: "sum"
      CarbSize: "sum"

# Evaluation configuration
evaluation:
  target_glucose_range: [70, 180] # mg/dL
  hypoglycemia_threshold: 70 # mg/dL
  hyperglycemia_threshold: 180 # mg/dL
  metrics_output_dir: "reports/metrics"

# Pipeline orchestration configuration
pipeline:
  skip_stages: [] # List of stages to skip
  parallel_stages: [] # List of stages to run in parallel

# Parallel processing configuration
parallel_processing:
  max_workers: 4 # Maximum number of parallel workers
  use_processes: true # Use processes instead of threads
  chunk_size: 1000 # Default chunk size for parallel processing
  memory_limit_gb: 4.0 # Memory limit in GB

# Error recovery configuration
error_recovery:
  max_retries: 3 # Maximum number of retries per stage
  retry_delay: 60 # Delay between retries in seconds
  checkpoint_dir: "checkpoints" # Directory for saving checkpoints
  error_log_dir: "logs/errors" # Directory for error logs

# Output configuration
output:
  base_dir: "outputs" # Base directory for all outputs
  save_intermediate: true # Save intermediate results
  cleanup_temp: true # Clean up temporary files
