# Default configuration for the diabetes LSTM pipeline
# Optimized for speed while maintaining reasonable performance

# Data configuration
data:
  raw_data_path: "data/raw"
  processed_data_path: "data/processed"
  dataset_url: "https://prod-dcd-datasets-cache-zipfiles.s3.eu-west-1.amazonaws.com/gk9m674wcx-1.zip"
  force_download: false

# Logging configuration
logging:
  level: "WARNING"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/pipeline.log"

# Model configuration - Optimized for speed
model:
  sequence_length: 12
  prediction_horizon: 1
  lstm_units: [64, 32]
  dropout_rate: 0.1
  recurrent_dropout: 0.05
  dense_units: [32, 16]
  activation: "relu"
  output_activation: "linear"
  learning_rate: 0.002
  l1_regularization: 0.0
  l2_regularization: 0.0005

# Training configuration - Optimized for speed
training:
  batch_size: 128
  epochs: 10
  validation_split: 0.15
  early_stopping_patience: 5
  lr_patience: 3
  verbose: 1

# Random seed for reproducibility
random_seed: 42

# Data validation configuration - Simplified for speed
validation:
  report_output_dir: "reports"
  zscore_threshold: 3.0
  contamination: 0.05
  required_columns:
    - "EventDateTime"
    - "DeviceMode"
    - "BolusType"
    - "Basal"
    - "CorrectionDelivered"
    - "TotalBolusInsulinDelivered"
    - "FoodDelivered"
    - "CarbSize"
    - "CGM"

# Data preprocessing configuration - Optimized for speed
preprocessing:
  missing_values:
    strategies:
      CGM: "interpolation"
      Basal: "forward_fill"
      TotalBolusInsulinDelivered: "zero_fill"
      CorrectionDelivered: "zero_fill"
      FoodDelivered: "zero_fill"
      CarbSize: "zero_fill"
    interpolation_method: "linear"
    max_gap_minutes: 30

  outliers:
    detection_methods: ["iqr"]
    treatment_method: "clip"
    zscore_threshold: 3.0
    iqr_multiplier: 1.5
    contamination: 0.05
    column_settings:
      CGM:
        min_value: 40
        max_value: 400
        detection_methods: ["iqr"]
        treatment_method: "clip"

  cleaning:
    duplicate_strategy: "keep_last"
    time_tolerance_seconds: 60
    participant_column: "participant_id"

  resampling:
    target_frequency: "10min"
    participant_column: "participant_id"
    aggregation_methods:
      CGM: "mean"
      Basal: "mean"
      TotalBolusInsulinDelivered: "sum"
      CorrectionDelivered: "sum"
      FoodDelivered: "sum"
      CarbSize: "sum"

# Feature engineering configuration - Simplified for speed
feature_engineering:
  temporal:
    include_time_features: true
    include_cyclical_features: false
    max_lag_hours: 2

  insulin:
    include_cumulative_features: true
    include_ratios: false
    max_cumulative_hours: 3

  glucose:
    include_trends: true
    include_variability: false
    include_time_in_range: false

  lag:
    max_lag_steps: 6
    include_rolling_stats: false

  scaling:
    type: "standard"
    handle_outliers: false

# Sequence generation configuration - Optimized for speed
sequence_generation:
  sequence_length: 12
  prediction_horizon: 1
  target_column: "CGM"
  sampling_interval: 10
  min_sequences_per_participant: 10

# Splitting configuration
splitting:
  train_ratio: 0.7
  val_ratio: 0.15
  test_ratio: 0.15
  random_seed: 42
  split_strategy: "participant"

# Evaluation configuration
evaluation:
  target_glucose_range: [70, 180] # mg/dL
  hypoglycemia_threshold: 70 # mg/dL
  hyperglycemia_threshold: 180 # mg/dL
  metrics_output_dir: "reports/metrics"

# Pipeline orchestration configuration
pipeline:
  skip_stages: [] # Can add stages to skip if needed
  parallel_stages: ["preprocessing", "feature_engineering"] # Enable parallel processing

# Parallel processing configuration - Optimized for speed
parallel_processing:
  max_workers: 8
  use_processes: true
  chunk_size: 2000
  memory_limit_gb: 8.0

# Error recovery configuration
error_recovery:
  max_retries: 2
  retry_delay: 30
  checkpoint_dir: "checkpoints"
  error_log_dir: "logs/errors"

# Output configuration
output:
  base_dir: "outputs"
  save_intermediate: false
  cleanup_temp: true

# Model persistence configuration
model_persistence:
  base_dir: "models"
  max_versions_per_model: 3
  auto_cleanup: true
  save_format: "keras"
  compression: false
  include_training_history: false

# TensorFlow optimization settings
tensorflow:
  mixed_precision: true
  memory_growth: true
  xla_optimization: true
  num_parallel_calls: 4
  prefetch_buffer_size: 2
